#!/bin/bash
echo "SOURCE_COMMIT: $SOURCE_COMMIT"
echo "DOCKER_TAG: $DOCKER_TAG"
if [[ -z "$SOURCE_COMMIT" ]]; then
	SOURCE_COMMIT=$(git rev-parse HEAD)
fi
case "$DOCKER_TAG" in
	master|latest) tag=master ;;
	*) tag=v$DOCKER_TAG ;;
esac
docker build -t $IMAGE_NAME --build-arg SOURCE_COMMIT=$SOURCE_COMMIT --build-arg SOURCE_TAG=$tag .
